/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: false,
  env: {
    NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY: process.env.NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY,
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    NEXT_PUBLIC_FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    NEXT_PUBLIC_FIREBASE_MESSAGING_APP_ID: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_APP_ID,
    NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID,
    NEXT_PUBLIC_MONGO_DATA_API_KEY: process.env.NEXT_PUBLIC_MONGO_DATA_API_KEY,
    NEXT_PUBLIC_MONGO_DATA_API_URL: process.env.NEXT_PUBLIC_MONGO_DATA_API_URL,
    NEXT_PUBLIC_MONGODB_DATA_SOURCE: process.env.NEXT_PUBLIC_MONGODB_DATA_SOURCE,
    NEXT_PUBLIC_ADMIN_ID: process.env.NEXT_PUBLIC_ADMIN_ID,
    NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME,
    NEXT_PUBLIC_CLOUDINARY_API_KEY: process.env.NEXT_PUBLIC_CLOUDINARY_API_KEY,
    NEXT_PUBLIC_CLOUDINARY_API_SECRET: process.env.NEXT_PUBLIC_CLOUDINARY_API_SECRET,
  },
  i18n: {
    locales: ['en'],
    defaultLocale: 'en',
  },
  output: 'standalone'
}

module.exports = nextConfig
